=== DmitryPoverov/EpamTraining/src/main/resources/vouchers.xsd
<xs:schema attributeFormDefault="unqualified" targetNamespace="test" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="vouchers">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="voucher" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="country"/>
              <xs:element type="xs:byte" name="numberOfDays"/>
              <xs:element name="hotelCharacteristics">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:byte" name="numberOfStars"/>
                    <xs:element type="xs:string" name="roomType"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:short" name="cost"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== DmitryPoverov/EpamTraining/src/main/resources/vouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<vouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="test"
          xsi:schemaLocation="test vouchers.xsd">
    <voucher>
        <country>Mexico</country>
        <numberOfDays>10</numberOfDays>
        <hotelCharacteristics>
            <numberOfStars>5</numberOfStars>
            <roomType>triple</roomType>
        </hotelCharacteristics>
        <cost>500</cost>
    </voucher>
    <voucher>
        <country>USA</country>
        <numberOfDays>2</numberOfDays>
        <hotelCharacteristics>
            <numberOfStars>4</numberOfStars>
            <roomType>double</roomType>
        </hotelCharacteristics>
        <cost>1000</cost>
    </voucher>
</vouchers>
